import Head from "next/head";
import Image from "next/image";

import AuthForm from "../components/AuthForm";
import Landing from "../components/Landing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=" flex justify-center bg-gray-100 min-h-screen border-solid border-2 border-sky-500">
        {/* <AuthForm /> */}
        <Landing />
      </main>
    </>
  );
}

// TODO: BUG - After authed, if at dashboard and refresh page - ERR
