import Head from "next/head";
import Image from "next/image";

import AuthForm from "../components/AuthForm";
import Landing from "../components/landing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <AuthForm /> */}
      <Landing />
    </>
  );
}

// TODO: BUG - After authed, if at dashboard and refresh page - ERR
