import Head from "next/head";
import Image from "next/image";
import { useState, useEffect, useCallback, useContext } from "react";
import { useRouter } from "next/router";
import jwt_decode from "jwt-decode";

import { User_data } from "../../context/appContext";

import Sidebar from "../../components/Sidebar";
import Header from "../../components/Header";
import TopCards from "../../components/TopCards";
import BarChart from "../../components/BarChart";
import RecentOrders from "../../components/RecentOrders";

export default function Home() {
  const { isAuthenticated, accessToken } = useContext(User_data);

  // const [isLoading, setIsLoading] = useState(true);
  var router = useRouter();

  useEffect(() => {
    if (!isAuthenticated) {
      return router.push("/");
    }
  }, [isAuthenticated]);

  console.log(accessToken);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Sidebar>
        {!isAuthenticated ? (
          <div>Loading ...</div>
        ) : (
          <main className="bg-gray-100 min-h-screen">
            <Header name={accessToken.userName} />
            <TopCards />
            {/* <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <BarChart />
          <RecentOrders />
        </div> */}
          </main>
        )}
      </Sidebar>
    </>
  );
}
